### ISSUE TITLE
[Main] 메인 페이지 화면 구현

### ISSUE THREAD

**Issue by yeriinnn** [Plick-pop-in/poppin-fe#1]
## ISSUE
- 메인 페이지 화면 구현

## To-do
- [x] 공통적으로 사용될 헤더 구현
- [x]  진행중인 팝업(스토어) 랜덤 이미지 구현(자동 슬라이드 5개)
- [x]  진행중인 팝업 top 3
- [x] 진행중인 전국 팝업 스토어 

## 참고사항 및 체크포인트
- [x] 이미지 슬라이더 좌우 버튼 위치 수정 필요
- [x] Top3 박스내의 하트안뜨는 오류 수정 필요
