### ISSUE TITLE
[Chat] 실시간 채팅 (메시지 주고 받는) 화면 및 기능 구현

### ISSUE THREAD

**Issue by yeriinnn** [Plick-pop-in/poppin-fe#2]
## ISSUE
- 실시간 채팅 (메시지 주고 받는) 화면 구현

## To-do
- [x] 실시간 채팅 (메시지 주고 받는) 화면 구현_로컬
- [x] 로컬->배포주소 변경
- [x] ui 수정
- [x] 라이브 화면에서 join 버튼 클릭 시 해당 chat으로 이동

## 참고사항 및 체크포인트
기능 개발하면서 동시에 디자인 진행해야할 듯
