### ISSUE TITLE
[Popup] 팝업 스토어 상세 정보 화면 구현

### ISSUE THREAD

**Issue by Byunseoyoon** [Plick-pop-in/poppin-fe#3]
## ISSUE
- 팝업 스토어 상세 정보 보여주는 화면

## To-do
- [x] 팝업 스토어 이름 및 기한, 위치
- [x] 채팅방 연결 버튼
- [x] 팝업 스토어 슬라이드 이미지
- [x] 운영 시간
- [x] 팝업스토어 상세 소개 글
 

## 참고사항 및 체크포인트
