### ISSUE TITLE
[Main] 메인페이지 API 연결

### ISSUE THREAD

**Issue by yeriinnn** [Plick-pop-in/poppin-fe#40]
## ISSUE
- 메인페이지 API 연결

## To-do
- [x]  진행중인 팝업(스토어) 랜덤 이미지 구현(자동 슬라이드 5개)
- [x]  팝업 좋아요 top 3
- [x]  좋아요 top3 팝업 클릭한 경우 각각의 상세페이지로 이동
- [x] 진행중인 전국 팝업 스토어 

## 참고사항 및 체크포인트
디테일한 요소는 추후 수정 예정
