### ISSUE TITLE
[Common]  Footer 디자인

### ISSUE THREAD

**Issue by KangHyorim** [Plick-pop-in/poppin-fe#7]
## ISSUE
- footer 화면 구현

## To-do
- [x] 배치 요소들 구현
- [x] 버튼 클릭 시 링크 이동
- [X] 언어 변경 드롭박스 구현

## 참고사항 및 체크포인트
- [x] 윈도우 크기 조정 시 로고 위치 고려
- [x] 마이페이지 하위 링크 추가 필요
